"""lexi domain schema

Revision ID: 20260724_01
Revises:
Create Date: 2026-07-25 11:34:54.280991
"""

import sqlalchemy as sa
from alembic import op

revision = "20260724_01"
down_revision = None
branch_labels = None
depends_on = None


def _schema() -> str:
    """The configured domain schema, resolved by the alembic environment."""
    from alembic import context

    return context.config.attributes["lexi_schema"]


def _qualified(target: str) -> str:
    """Qualify a foreign-key target with the configured domain schema."""
    return f"{_schema()}.{target}"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_kind", sa.String(length=32), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("params", sa.String(length=64), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("text_value", sa.Text(), nullable=True),
        sa.Column("file_path", sa.Text(), nullable=True),
        sa.Column("meta", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_kind", "source_id", "kind", "params", name="uq_asset_identity"),
        schema=_schema(),
    )
    op.create_index(
        op.f("ix_assets_source_id"), "assets", ["source_id"], unique=False, schema=_schema()
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("tag_key", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema=_schema(),
    )
    op.create_index(op.f("ix_tags_tag_key"), "tags", ["tag_key"], unique=True, schema=_schema())
    op.create_table(
        "themes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("theme_key", sa.String(length=255), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("style_prompt", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("tone", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema=_schema(),
    )
    op.create_index(
        op.f("ix_themes_theme_key"), "themes", ["theme_key"], unique=True, schema=_schema()
    )
    op.create_table(
        "words",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("norm", sa.Text(), nullable=False),
        sa.Column("match_key", sa.String(length=512), nullable=False),
        sa.Column("entry_type", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("generation_epoch", sa.Integer(), nullable=False),
        sa.Column("pos", sa.String(length=32), nullable=True),
        sa.Column("cambridge_word_id", sa.Integer(), nullable=True),
        sa.Column("error_msg", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema=_schema(),
    )
    op.create_index(
        op.f("ix_words_match_key"), "words", ["match_key"], unique=True, schema=_schema()
    )
    op.create_table(
        "senses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("word_id", sa.Integer(), nullable=False),
        sa.Column("definition", sa.Text(), nullable=False),
        sa.Column("tier", sa.String(length=16), nullable=False),
        sa.Column("sense_order", sa.Integer(), nullable=False),
        sa.Column("pos", sa.String(length=32), nullable=True),
        sa.Column("cefr_level", sa.String(length=8), nullable=True),
        sa.Column("ipa_uk", sa.String(length=64), nullable=True),
        sa.Column("ipa_us", sa.String(length=64), nullable=True),
        sa.Column("guideword", sa.String(length=64), nullable=True),
        sa.Column("grammar", sa.String(length=128), nullable=True),
        sa.Column("register", sa.String(length=32), nullable=True),
        sa.Column("connotation", sa.String(length=16), nullable=True),
        sa.Column("domain", sa.String(length=64), nullable=True),
        sa.Column("usage_note", sa.String(length=255), nullable=True),
        sa.Column("embedding", sa.LargeBinary(), nullable=True),
        sa.Column("embedding_model", sa.String(length=128), nullable=True),
        sa.Column("embedding_dim", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["word_id"], [_qualified("words.id")], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema=_schema(),
    )
    op.create_table(
        "word_aliases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("word_id", sa.Integer(), nullable=False),
        sa.Column("alias_norm", sa.Text(), nullable=False),
        sa.Column("alias_match_key", sa.String(length=512), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("dialect", sa.String(length=8), nullable=True),
        sa.ForeignKeyConstraint(["word_id"], [_qualified("words.id")], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("word_id", "alias_match_key", name="uq_alias_word_key"),
        schema=_schema(),
    )
    op.create_index(
        op.f("ix_word_aliases_alias_match_key"),
        "word_aliases",
        ["alias_match_key"],
        unique=False,
        schema=_schema(),
    )
    op.create_table(
        "word_relation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("from_word_id", sa.Integer(), nullable=False),
        sa.Column("to_word_id", sa.Integer(), nullable=False),
        sa.Column("rel_type", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["from_word_id"], [_qualified("words.id")], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["to_word_id"], [_qualified("words.id")], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("from_word_id", "to_word_id", "rel_type", name="uq_link_triple"),
        schema=_schema(),
    )
    op.create_table(
        "word_tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("word_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["tag_id"], [_qualified("tags.id")], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["word_id"], [_qualified("words.id")], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("word_id", "tag_id", name="uq_word_tag"),
        schema=_schema(),
    )
    op.create_table(
        "collocations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sense_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("collocation_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["sense_id"], [_qualified("senses.id")], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema=_schema(),
    )
    op.create_table(
        "examples",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sense_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("example_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["sense_id"], [_qualified("senses.id")], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema=_schema(),
    )
    op.create_table(
        "questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("word_id", sa.Integer(), nullable=False),
        sa.Column("sense_id", sa.Integer(), nullable=True),
        sa.Column("type_id", sa.String(length=32), nullable=False),
        sa.Column("render_format", sa.String(length=16), nullable=False),
        sa.Column("difficulty_level", sa.Integer(), nullable=False),
        sa.Column("interaction_mode", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["sense_id"], [_qualified("senses.id")], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["word_id"], [_qualified("words.id")], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "sense_id", "type_id", "difficulty_level", "content_hash", name="uq_question_content"
        ),
        schema=_schema(),
    )
    op.create_index(
        op.f("ix_questions_word_id"), "questions", ["word_id"], unique=False, schema=_schema()
    )
    op.create_table(
        "sense_forms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sense_id", sa.Integer(), nullable=False),
        sa.Column("inf", sa.String(length=24), nullable=False),
        sa.Column("surface", sa.Text(), nullable=False),
        sa.Column("form_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["sense_id"], [_qualified("senses.id")], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema=_schema(),
    )
    op.create_table(
        "sense_reference",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sense_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("source_ref", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(["sense_id"], [_qualified("senses.id")], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema=_schema(),
    )
    op.create_table(
        "sense_relation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("from_sense_id", sa.Integer(), nullable=False),
        sa.Column("to_word_id", sa.Integer(), nullable=False),
        sa.Column("to_sense_id", sa.Integer(), nullable=True),
        sa.Column("rel_type", sa.String(length=32), nullable=False),
        sa.Column("gloss", sa.Text(), nullable=False),
        sa.Column("target_hash", sa.String(length=64), nullable=True),
        sa.Column("resolve_attempted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["from_sense_id"], [_qualified("senses.id")], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["to_sense_id"], [_qualified("senses.id")], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["to_word_id"], [_qualified("words.id")], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("from_sense_id", "to_word_id", "rel_type", name="uq_sense_rel"),
        schema=_schema(),
    )
    op.create_table(
        "themed_senses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sense_id", sa.Integer(), nullable=False),
        sa.Column("theme_id", sa.Integer(), nullable=False),
        sa.Column("definition", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["sense_id"], [_qualified("senses.id")], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["theme_id"], [_qualified("themes.id")], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sense_id", "theme_id", name="uq_themed_sense"),
        schema=_schema(),
    )
    op.create_table(
        "themed_examples",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("themed_sense_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("example_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["themed_sense_id"], [_qualified("themed_senses.id")], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema=_schema(),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("themed_examples", schema=_schema())
    op.drop_table("themed_senses", schema=_schema())
    op.drop_table("sense_relation", schema=_schema())
    op.drop_table("sense_reference", schema=_schema())
    op.drop_table("sense_forms", schema=_schema())
    op.drop_index(op.f("ix_questions_word_id"), table_name="questions", schema=_schema())
    op.drop_table("questions", schema=_schema())
    op.drop_table("examples", schema=_schema())
    op.drop_table("collocations", schema=_schema())
    op.drop_table("word_tags", schema=_schema())
    op.drop_table("word_relation", schema=_schema())
    op.drop_index(
        op.f("ix_word_aliases_alias_match_key"), table_name="word_aliases", schema=_schema()
    )
    op.drop_table("word_aliases", schema=_schema())
    op.drop_table("senses", schema=_schema())
    op.drop_index(op.f("ix_words_match_key"), table_name="words", schema=_schema())
    op.drop_table("words", schema=_schema())
    op.drop_index(op.f("ix_themes_theme_key"), table_name="themes", schema=_schema())
    op.drop_table("themes", schema=_schema())
    op.drop_index(op.f("ix_tags_tag_key"), table_name="tags", schema=_schema())
    op.drop_table("tags", schema=_schema())
    op.drop_index(op.f("ix_assets_source_id"), table_name="assets", schema=_schema())
    op.drop_table("assets", schema=_schema())
    # ### end Alembic commands ###
