# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from lexi_service.proto.lexi.v1 import lexi_pb2 as lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in lexi_service/proto/lexi/v1/lexi_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LexiServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Search = channel.unary_unary(
                '/lexi.v1.LexiService/Search',
                request_serializer=lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.SearchRequest.SerializeToString,
                response_deserializer=lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.Lookup = channel.unary_unary(
                '/lexi.v1.LexiService/Lookup',
                request_serializer=lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.LookupRequest.SerializeToString,
                response_deserializer=lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.EntryResponse.FromString,
                _registered_method=True)
        self.GetSenses = channel.unary_unary(
                '/lexi.v1.LexiService/GetSenses',
                request_serializer=lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.GetSensesRequest.SerializeToString,
                response_deserializer=lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.SensesResponse.FromString,
                _registered_method=True)
        self.SubmitGenerate = channel.unary_unary(
                '/lexi.v1.LexiService/SubmitGenerate',
                request_serializer=lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.SubmitGenerateRequest.SerializeToString,
                response_deserializer=lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.JobResponse.FromString,
                _registered_method=True)
        self.GetJob = channel.unary_unary(
                '/lexi.v1.LexiService/GetJob',
                request_serializer=lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.GetJobRequest.SerializeToString,
                response_deserializer=lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.JobResponse.FromString,
                _registered_method=True)
        self.SubmitTranslation = channel.unary_unary(
                '/lexi.v1.LexiService/SubmitTranslation',
                request_serializer=lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.SubmitTranslationRequest.SerializeToString,
                response_deserializer=lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.JobResponse.FromString,
                _registered_method=True)
        self.Stats = channel.unary_unary(
                '/lexi.v1.LexiService/Stats',
                request_serializer=lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.StatsRequest.SerializeToString,
                response_deserializer=lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.StatsResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/lexi.v1.LexiService/Health',
                request_serializer=lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.HealthRequest.SerializeToString,
                response_deserializer=lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Readiness = channel.unary_unary(
                '/lexi.v1.LexiService/Readiness',
                request_serializer=lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.HealthRequest.SerializeToString,
                response_deserializer=lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.HealthResponse.FromString,
                _registered_method=True)


class LexiServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Lookup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSenses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitGenerate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitTranslation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Readiness(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LexiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.SearchRequest.FromString,
                    response_serializer=lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.SearchResponse.SerializeToString,
            ),
            'Lookup': grpc.unary_unary_rpc_method_handler(
                    servicer.Lookup,
                    request_deserializer=lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.LookupRequest.FromString,
                    response_serializer=lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.EntryResponse.SerializeToString,
            ),
            'GetSenses': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSenses,
                    request_deserializer=lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.GetSensesRequest.FromString,
                    response_serializer=lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.SensesResponse.SerializeToString,
            ),
            'SubmitGenerate': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitGenerate,
                    request_deserializer=lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.SubmitGenerateRequest.FromString,
                    response_serializer=lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.JobResponse.SerializeToString,
            ),
            'GetJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJob,
                    request_deserializer=lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.GetJobRequest.FromString,
                    response_serializer=lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.JobResponse.SerializeToString,
            ),
            'SubmitTranslation': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTranslation,
                    request_deserializer=lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.SubmitTranslationRequest.FromString,
                    response_serializer=lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.JobResponse.SerializeToString,
            ),
            'Stats': grpc.unary_unary_rpc_method_handler(
                    servicer.Stats,
                    request_deserializer=lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.StatsRequest.FromString,
                    response_serializer=lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.StatsResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.HealthRequest.FromString,
                    response_serializer=lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.HealthResponse.SerializeToString,
            ),
            'Readiness': grpc.unary_unary_rpc_method_handler(
                    servicer.Readiness,
                    request_deserializer=lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.HealthRequest.FromString,
                    response_serializer=lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lexi.v1.LexiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lexi.v1.LexiService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LexiService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lexi.v1.LexiService/Search',
            lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.SearchRequest.SerializeToString,
            lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Lookup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lexi.v1.LexiService/Lookup',
            lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.LookupRequest.SerializeToString,
            lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.EntryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSenses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lexi.v1.LexiService/GetSenses',
            lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.GetSensesRequest.SerializeToString,
            lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.SensesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitGenerate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lexi.v1.LexiService/SubmitGenerate',
            lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.SubmitGenerateRequest.SerializeToString,
            lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.JobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lexi.v1.LexiService/GetJob',
            lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.GetJobRequest.SerializeToString,
            lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.JobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitTranslation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lexi.v1.LexiService/SubmitTranslation',
            lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.SubmitTranslationRequest.SerializeToString,
            lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.JobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lexi.v1.LexiService/Stats',
            lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.StatsRequest.SerializeToString,
            lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.StatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lexi.v1.LexiService/Health',
            lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.HealthRequest.SerializeToString,
            lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Readiness(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lexi.v1.LexiService/Readiness',
            lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.HealthRequest.SerializeToString,
            lexi__service_dot_proto_dot_lexi_dot_v1_dot_lexi__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
