"""Focused checks for the library-owned PostgreSQL migration surface."""

import ast
import subprocess
import sys
from pathlib import Path

import pytest
from sqlalchemy import UniqueConstraint, inspect

from lexi_ai.config import Settings
from lexi_ai.db import create_engine, init_models
from lexi_ai.infrastructure.db.models import Question, Sense
from tests.conftest import PG_SCHEMA, requires_asyncpg_driver, requires_postgres

ROOT = Path(__file__).resolve().parents[1]
ALEMBIC_CONFIG = ROOT / "lexi_ai" / "migrations" / "alembic.ini"
MIGRATIONS = ROOT / "lexi_ai" / "migrations"


def _alembic(*args: str) -> str:
    completed = subprocess.run(
        [str(Path(sys.executable).with_name("alembic")), "-c", str(ALEMBIC_CONFIG), *args],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    return completed.stdout


@requires_asyncpg_driver
def test_postgres_engine_translates_the_default_schema():
    engine = create_engine(Settings(db_url="postgresql+asyncpg://unused", db_schema="dictionary"))
    try:
        assert engine.sync_engine._execution_options["schema_translate_map"] == {None: "dictionary"}
    finally:
        engine.sync_engine.dispose()


def test_sqlite_engine_does_not_translate_the_default_schema():
    engine = create_engine(Settings(db_url="sqlite+aiosqlite://"))
    try:
        assert "schema_translate_map" not in engine.sync_engine._execution_options
    finally:
        engine.sync_engine.dispose()


@requires_asyncpg_driver
async def test_init_models_rejects_postgres_bootstrap_ddl():
    engine = create_engine(Settings(db_url="postgresql+asyncpg://unused"))
    try:
        with pytest.raises(RuntimeError, match="SQLite"):
            await init_models(engine)
    finally:
        await engine.dispose()


def test_domain_migrations_render_the_configured_schema_offline():
    upgrade = _alembic("-x", "schema=dictionary", "upgrade", "head", "--sql")

    assert "CREATE SCHEMA IF NOT EXISTS dictionary" in upgrade
    assert "CREATE TABLE dictionary.alembic_version" in upgrade
    assert "CREATE TABLE dictionary.words" in upgrade
    assert upgrade.index("CREATE SCHEMA") < upgrade.index("CREATE TABLE dictionary.alembic_version")


def test_single_baseline_carries_the_question_contract_columns():
    upgrade = _alembic("-x", "schema=dictionary", "upgrade", "head", "--sql")

    assert "type_id" in upgrade
    assert "render_format" in upgrade
    assert "difficulty_level" in upgrade
    assert "interaction_mode" in upgrade
    assert "content_hash" in upgrade
    assert "uq_question_content" in upgrade


def test_history_is_one_generated_baseline_plus_forward_revisions():
    """The ORM is the only schema source, and the history starts from one baseline.

    The schema previously had three sources — a hand-written frozen copy, a
    baseline that called it, and a follow-up revision reshaping columns the frozen
    copy still declared. They drifted. The baseline is now autogenerated from the
    ORM and every later change is an ordinary forward revision on top of it.
    """
    revisions = sorted(
        path.name for path in (MIGRATIONS / "versions").glob("*.py") if path.name != "__init__.py"
    )

    assert revisions[0] == "20260724_01_lexi_domain_schema.py"
    assert not (MIGRATIONS / "frozen_schema.py").exists()


def test_head_leaves_no_sense_embedding_columns():
    """Sense vectors live in the vector index, so the schema must not carry them.

    The ORM is the durable statement of that (autogenerate would re-add a column
    the models declare), and the migration chain has to actually drop what the
    baseline created.
    """
    assert not {"embedding", "embedding_model", "embedding_dim"} & set(
        Sense.__table__.columns.keys()
    )

    upgrade = _alembic("-x", "schema=dictionary", "upgrade", "head", "--sql")
    for column in ("embedding", "embedding_model", "embedding_dim"):
        assert f"DROP COLUMN {column}" in upgrade


def test_baseline_renders_literal_ddl_without_importing_the_orm():
    """The baseline must stay immutable once released.

    Autogenerate emits literal column definitions, so a later model change cannot
    retroactively alter what this revision creates. Importing the ORM here would
    break that: the revision would describe whatever the models say today.
    """
    baseline = (MIGRATIONS / "versions" / "20260724_01_lexi_domain_schema.py").read_text()

    assert "lexi_ai.infrastructure.db.models" not in baseline
    assert "Base.metadata" not in baseline
    assert "op.create_table(" in baseline


def test_online_migrations_use_a_committing_engine_transaction():
    env = ast.parse((MIGRATIONS / "env.py").read_text())
    runner = next(
        node
        for node in env.body
        if isinstance(node, ast.AsyncFunctionDef) and node.name == "run_migrations_online"
    )
    transaction = next(node for node in ast.walk(runner) if isinstance(node, ast.AsyncWith))
    call = transaction.items[0].context_expr

    assert isinstance(call, ast.Call)
    assert isinstance(call.func, ast.Attribute)
    assert call.func.attr == "begin"


def _reflected_question_schema(connection):
    inspector = inspect(connection)
    columns = {
        column["name"]: column["nullable"]
        for column in inspector.get_columns("questions", schema=PG_SCHEMA)
    }
    primary_key = tuple(
        inspector.get_pk_constraint("questions", schema=PG_SCHEMA)["constrained_columns"]
    )
    foreign_keys = {
        (
            tuple(foreign_key["constrained_columns"]),
            foreign_key["referred_table"],
            tuple(foreign_key["referred_columns"]),
        )
        for foreign_key in inspector.get_foreign_keys("questions", schema=PG_SCHEMA)
    }
    unique_constraints = {
        constraint["name"]: tuple(constraint["column_names"])
        for constraint in inspector.get_unique_constraints("questions", schema=PG_SCHEMA)
    }
    return columns, primary_key, foreign_keys, unique_constraints


@requires_postgres
async def test_postgres_question_schema_matches_orm(pg_session_factory):
    """Execute the full migration chain and compare its question schema to the ORM."""
    async with pg_session_factory() as session:
        connection = await session.connection()
        actual = await connection.run_sync(_reflected_question_schema)

    expected_columns = {column.name: column.nullable for column in Question.__table__.columns}
    expected_primary_key = tuple(column.name for column in Question.__table__.primary_key)
    expected_foreign_keys = {
        (
            tuple(element.parent.name for element in constraint.elements),
            next(iter(constraint.elements)).column.table.name,
            tuple(element.column.name for element in constraint.elements),
        )
        for constraint in Question.__table__.foreign_key_constraints
    }
    expected_unique_constraints = {
        constraint.name: tuple(column.name for column in constraint.columns)
        for constraint in Question.__table__.constraints
        if isinstance(constraint, UniqueConstraint)
    }

    assert actual == (
        expected_columns,
        expected_primary_key,
        expected_foreign_keys,
        expected_unique_constraints,
    )
